"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import { CalendarPlus,Edit2,Plus,Trash2 } from "lucide-react";
import { getAll,save,remove } from "@/services/api";
import type { AppData,Attendance as AttendanceRecord,SalaryRate } from "@/types";
import { currentMonth,todayISO,formatDate,dateRange } from "@/lib/dates";
import { money,number } from "@/lib/format";
import { Modal } from "./Modal";
import { Toast } from "./Toast";
import { Loading } from "./Loading";
const blank:AppData={cash:[],accounts:[],investments:[],loans:[],companies:[],rates:[],attendance:[]};
const hours24=Array.from({length:24},(_,i)=>String(i).padStart(2,"0"));
const minutes=Array.from({length:60},(_,i)=>String(i).padStart(2,"0"));
export function AttendancePage(){
 const [data,setData]=useState<AppData>(),[busy,setBusy]=useState(true),[loadError,setLoadError]=useState(""),[month,setMonth]=useState(currentMonth()),[company,setCompany]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState(""),[preset,setPreset]=useState(""),[modal,setModal]=useState(false),[editing,setEditing]=useState<AttendanceRecord>(),[msg,setMsg]=useState(""),[kind,setKind]=useState<"success"|"error">("success"),[saving,setSaving]=useState(false);
 const refresh=useCallback(async()=>{setBusy(true);setLoadError("");try{setData(await getAll())}catch(e){const message=(e as Error).message;setLoadError(message);setKind("error");setMsg(message)}finally{setBusy(false)}},[]);
 useEffect(()=>{refresh()},[refresh]);const d=data||blank;
 const shown=useMemo(()=>d.attendance.filter(x=>(!month||x.date.startsWith(month))&&(!company||x.companyId===company)&&(!from||x.date>=from)&&(!to||x.date<=to)).sort((a,b)=>b.date.localeCompare(a.date)),[d,month,company,from,to]);
 const hours=shown.reduce((s,x)=>s+x.hours,0),pay=shown.reduce((s,x)=>s+x.pay,0);
 function rateFor(companyId:string,date:string):SalaryRate|undefined{return d.rates.filter(r=>r.companyId===companyId&&r.effectiveFrom<=date&&(!r.effectiveTo||r.effectiveTo>=date)).sort((a,b)=>b.effectiveFrom.localeCompare(a.effectiveFrom))[0]}
 function formSubmit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget),v:any={};fd.forEach((val,k)=>v[k]=val);setSaving(true);save("attendance",v,editing?.id).then(async()=>{setKind("success");setMsg(editing?"Đã cập nhật ngày công.":"Đã thêm ngày công.");setModal(false);setEditing(undefined);await refresh()}).catch(e=>{setKind("error");setMsg(e.message)}).finally(()=>setSaving(false))}
 async function del(x:AttendanceRecord){if(!window.confirm("Bạn có chắc muốn xóa ngày công "+formatDate(x.date)+"? Dòng sẽ bị xóa khỏi Google Sheets."))return;try{await remove("attendance",x.id);setKind("success");setMsg("Đã xóa ngày công.");await refresh()}catch(e){setKind("error");setMsg((e as Error).message)}}
 const ratesUsed=new Set(shown.map(x=>x.salaryRate));
 return <><header className="page-top"><div><div className="eyebrow">Theo dõi giờ làm</div><h1 className="page-title">Chấm công</h1><p className="page-subtitle">Ghi nhận giờ làm và mức lương có hiệu lực theo từng ngày.</p></div><button className="button primary" onClick={()=>{setEditing(undefined);setModal(true)}}><Plus size={16}/> Thêm ngày công</button></header>
 <section className="metrics" style={{gridTemplateColumns:"repeat(3,minmax(0,1fr))"}}><div className="card metric"><div className="metric-head">Ngày công</div><div className="metric-value">{shown.length} <span style={{fontSize:12,fontWeight:500}}>ngày</span></div><div className="metric-note">Theo bộ lọc hiện tại</div></div><div className="card metric"><div className="metric-head">Tổng số giờ</div><div className="metric-value">{number(hours)} <span style={{fontSize:12,fontWeight:500}}>giờ</span></div><div className="metric-note">Đã ghi nhận</div></div><div className="card metric total"><div className="metric-head">Tổng tiền công</div><div className="metric-value">{money(pay)}</div><div className="metric-note">{ratesUsed.size>1?"Nhiều mức lương trong kỳ":"Theo đơn giá đã lưu theo ngày"}</div></div></section>
 <div className="filter-bar"><div className="filters"><div className="field"><label>Thời gian</label><select className="input compact" value={preset||"month-filter"} onChange={e=>{const p=e.target.value;if(p==="month-filter"){setPreset("");setFrom("");setTo("");setMonth(currentMonth())}else{setPreset(p);setMonth("");const r=dateRange(p);setFrom(r.from);setTo(r.to)}}}><option value="today">Hôm nay</option><option value="week">Tuần này</option><option value="month">Tháng này</option><option value="previous">Tháng trước</option><option value="month-filter">Chọn tháng</option><option value="custom">Tùy chọn khoảng ngày</option></select></div>{!preset&&<div className="field"><label>Tháng</label><input className="input compact" type="month" value={month} onChange={e=>setMonth(e.target.value)}/></div>}<div className="field"><label>Công ty</label><select className="input compact" value={company} onChange={e=>setCompany(e.target.value)}><option value="">Tất cả công ty</option>{d.companies.map(c=><option key={c.id} value={c.id}>{c.name} ({c.id})</option>)}</select></div>{(preset==="custom"||preset!=="month-filter"&&preset!=="")&&<><div className="field"><label>Từ ngày</label><input className="input compact" type="date" value={from} onChange={e=>{setPreset("custom");setFrom(e.target.value)}}/></div><div className="field"><label>Đến ngày</label><input className="input compact" type="date" value={to} onChange={e=>{setPreset("custom");setTo(e.target.value)}}/></div></>}</div><span className="muted" style={{fontSize:11,paddingBottom:8}}>{shown.length} bản ghi</span></div>
 {busy&&!data?<Loading/>:loadError&&!data?<div className="error-box">{loadError}<br/><button className="button secondary small" style={{marginTop:12}} onClick={refresh}>Thử lại</button></div>:<div className="card table-card"><div className="table-scroll"><table className="data-table"><thead><tr><th>Ngày</th><th>Công ty</th><th>Bắt đầu</th><th>Kết thúc</th><th className="right">Số giờ</th><th className="right">Mức lương</th><th className="right">Tiền công</th><th>Trạng thái</th><th/></tr></thead><tbody>{shown.map(x=><tr key={x.id}><td>{formatDate(x.date)}</td><td><span className="pill gray">{d.companies.find(c=>c.id===x.companyId)?.name||x.companyId}</span></td><td>{x.startTime||"—"}</td><td>{x.endTime||"—"}</td><td className="right">{number(x.hours)}</td><td className="right">{money(x.salaryRate)}/giờ</td><td className="right amount-positive">{money(x.pay)}</td><td>{x.status||"—"}</td><td><div className="row-actions"><button className="icon-button" title="Sửa" onClick={()=>{setEditing(x);setModal(true)}}><Edit2 size={14}/></button><button className="icon-button" title="Xóa" onClick={()=>del(x)}><Trash2 size={14}/></button></div></td></tr>)}</tbody></table></div>{!shown.length&&<div className="empty">Không có ngày công trong bộ lọc này.</div>}</div>}
 {modal&&<AttendanceForm data={d} editing={editing} onClose={()=>{setModal(false);setEditing(undefined)}} onSubmit={formSubmit} saving={saving} rateFor={rateFor}/>}<Toast message={msg} kind={kind} onClose={()=>setMsg("")}/></>
}
function AttendanceForm({data,editing,onClose,onSubmit,saving,rateFor}:{data:AppData;editing?:AttendanceRecord;onClose:()=>void;onSubmit:(e:React.FormEvent<HTMLFormElement>)=>void;saving:boolean;rateFor:(c:string,d:string)=>SalaryRate|undefined}){
 const [date,setDate]=useState(editing?.date||todayISO()),[company,setCompany]=useState(editing?.companyId||data.companies.find(c=>c.active)?.id||""),[start,setStart]=useState(editing?.startTime||"09:00"),[end,setEnd]=useState(editing?.endTime||"17:00");
 const rate=rateFor(company,date),hours=Math.max(0,(timeMinutes(end)-timeMinutes(start))/60),pay=editing?.pay!==undefined&&editing.startTime===start&&editing.endTime===end&&editing.date===date&&editing.companyId===company?editing.pay:(rate?hours*rate.rate:0);
 return <Modal title={editing?"Sửa ngày công":"Thêm ngày công"} onClose={onClose}><form onSubmit={onSubmit}><div className="form-grid"><div className="field"><label>Ngày làm</label><input className="input" type="date" name="date" value={date} onChange={e=>setDate(e.target.value)} required/></div><div className="field"><label>Công ty</label><select className="input" name="companyId" value={company} onChange={e=>setCompany(e.target.value)} required><option value="">Chọn công ty</option>{data.companies.filter(c=>c.active).map(c=><option key={c.id} value={c.id}>{c.name} ({c.id})</option>)}</select></div><Time24Select label="Giờ bắt đầu" name="startTime" value={start} onChange={setStart}/><Time24Select label="Giờ kết thúc" name="endTime" value={end} onChange={setEnd}/><div className="field"><label>Trạng thái</label><select className="input" name="status" defaultValue={editing?.status||"Đi làm"}><option>Đi làm</option><option>Nghỉ có phép</option><option>Nghỉ không lương</option></select></div><div className="field"><label>Ghi chú</label><input className="input" name="note" defaultValue={editing?.note||""} placeholder="Không bắt buộc"/></div><div className="wide preview-box"><span>Số giờ <b>{number(hours)} giờ</b></span><span>Mức lương <b>{rate?money(rate.rate)+"/giờ":"Chưa thiết lập"}</b></span><span>Tiền công <b>{money(pay)}</b></span></div>{!rate&&<div className="wide muted" style={{fontSize:11}}>Chưa có mức lương hiệu lực. Vui lòng thêm mức lương ở trang Công ty & mức lương trước.</div>}</div><div className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>Hủy</button><button className="button primary" disabled={saving||!rate}>{saving?<><span className="spinner"/> Đang lưu</>:"Lưu ngày công"}</button></div></form></Modal>
}
function Time24Select({label,name,value,onChange}:{label:string;name:string;value:string;onChange:(value:string)=>void}){
 const [rawHour="00",rawMinute="00"]=value.split(":");
 const hour=rawHour.padStart(2,"0"),minute=rawMinute.padStart(2,"0");
 return <div className="field"><label>{label}</label><div style={{display:"grid",gridTemplateColumns:"1fr auto 1fr",alignItems:"center",gap:5}}><select className="input" aria-label={`${label} - giờ`} value={hour} onChange={e=>onChange(`${e.target.value}:${minute}`)} required>{hours24.map(x=><option key={x} value={x}>{x}</option>)}</select><span aria-hidden="true">:</span><select className="input" aria-label={`${label} - phút`} value={minute} onChange={e=>onChange(`${hour}:${e.target.value}`)} required>{minutes.map(x=><option key={x} value={x}>{x}</option>)}</select></div><input type="hidden" name={name} value={`${hour}:${minute}`}/></div>
}
function timeMinutes(s:string){const [h,m]=s.split(":").map(Number);return (h||0)*60+(m||0)}
