"use client";
import { useCallback,useEffect,useState } from "react";
import { Building2,Plus,Wallet } from "lucide-react";
import { getAll,save } from "@/services/api";
import type { AppData,Company } from "@/types";
import { formatDate,todayISO } from "@/lib/dates";
import { money } from "@/lib/format";
import { Modal } from "./Modal";
import { Toast } from "./Toast";
import { Loading } from "./Loading";
const empty:AppData={cash:[],accounts:[],investments:[],loans:[],companies:[],rates:[],attendance:[]};
export function CompaniesPage(){
 const [data,setData]=useState<AppData>(),[busy,setBusy]=useState(true),[companyForm,setCompanyForm]=useState(false),[rateCompany,setRateCompany]=useState<Company>(),[saving,setSaving]=useState(false),[msg,setMsg]=useState(""),[kind,setKind]=useState<"success"|"error">("success");
 const refresh=useCallback(async()=>{setBusy(true);try{setData(await getAll())}catch(e){setKind("error");setMsg((e as Error).message)}finally{setBusy(false)}},[]);
 useEffect(()=>{refresh()},[refresh]);const d=data||empty;
 async function submit(e:React.FormEvent<HTMLFormElement>,resource:"companies"|"salary-rates"){e.preventDefault();const fd=new FormData(e.currentTarget),v:any={};fd.forEach((value,key)=>v[key]=value);if(resource==="salary-rates")v.rate=Number(v.rate);if(resource==="companies")v.active=true;setSaving(true);try{await save(resource,v);setKind("success");setMsg(resource==="companies"?"Đã thêm công ty.":"Đã thêm mức lương.");setCompanyForm(false);setRateCompany(undefined);await refresh()}catch(err){setKind("error");setMsg((err as Error).message)}finally{setSaving(false)}}
 return <><header className="page-top"><div><div className="eyebrow">Cấu hình chấm công</div><h1 className="page-title">Công ty & mức lương</h1><p className="page-subtitle">Quản lý nơi làm việc và các giai đoạn đơn giá. Mỗi ngày công dùng mức đúng theo ngày.</p></div><button className="button primary" onClick={()=>setCompanyForm(true)}><Plus size={16}/> Thêm công ty</button></header>
 {busy&&!data?<Loading/>:<><div className="section-head"><div><h2 className="card-title">Danh sách công ty</h2><div className="card-caption">{d.companies.length} công ty trong sổ chấm công</div></div></div><div className="company-grid">{d.companies.map(c=>{const rates=d.rates.filter(r=>r.companyId===c.id).sort((a,b)=>b.effectiveFrom.localeCompare(a.effectiveFrom));return <section className="card company-card" key={c.id}><div className="card-head"><div style={{display:"flex",alignItems:"center",gap:10}}><span className="metric-icon"><Building2 size={16}/></span><div><div className="company-name">{c.name}</div><div className="card-caption">{c.id}</div></div></div><span className={"pill "+(!c.active?"gray":"")}>{c.active?"Đang hoạt động":"Ngừng hoạt động"}</span></div><div className="section-head" style={{margin:"17px 0 4px"}}><div className="card-title" style={{fontSize:12}}>Lịch sử mức lương</div><button className="button secondary small" onClick={()=>setRateCompany(c)}><Plus size={13}/> Thêm mức</button></div>{rates.length?rates.map(r=><div className="rate-line" key={r.id}><div><b>{formatDate(r.effectiveFrom)} – {r.effectiveTo?formatDate(r.effectiveTo):"hiện tại"}</b><div className="card-caption">{r.unit||"VND/giờ"}{r.note?" · "+r.note:""}</div></div><b>{money(r.rate)}/giờ</b></div>):<div className="empty" style={{padding:"16px 5px"}}>Chưa có mức lương.</div>}</section>})}</div>{!d.companies.length&&<div className="card empty">Chưa có công ty. Thêm công ty trước khi nhập chấm công.</div>}</>}
 {companyForm&&<Modal title="Thêm công ty" onClose={()=>setCompanyForm(false)}><form onSubmit={e=>submit(e,"companies")}><div className="form-grid"><div className="field wide"><label>Tên công ty</label><input className="input" name="name" autoFocus required placeholder="Ví dụ: Công ty ABC"/></div><div className="field wide"><label>Mã công ty (tự tạo nếu để trống)</label><input className="input" name="id" placeholder="Ví dụ: CT03"/></div><div className="field wide"><label>Ghi chú</label><input className="input" name="note"/></div></div><div className="modal-actions"><button type="button" className="button secondary" onClick={()=>setCompanyForm(false)}>Hủy</button><button className="button primary" disabled={saving}>{saving?"Đang lưu…":"Thêm công ty"}</button></div></form></Modal>}
 {rateCompany&&<Modal title={"Thêm mức lương · "+rateCompany.name} onClose={()=>setRateCompany(undefined)}><form onSubmit={e=>submit(e,"salary-rates")}><input type="hidden" name="companyId" value={rateCompany.id}/><div className="form-grid"><div className="field"><label>Có hiệu lực từ</label><input className="input" name="effectiveFrom" type="date" defaultValue={todayISO()} required/></div><div className="field"><label>Có hiệu lực đến (để trống nếu hiện tại)</label><input className="input" name="effectiveTo" type="date"/></div><div className="field"><label>Đơn giá theo giờ</label><input className="input" name="rate" type="number" min="0" step="any" required/></div><div className="field"><label>Đơn vị</label><input className="input" name="unit" defaultValue="VND/giờ" required/></div><div className="field wide"><label>Ghi chú</label><input className="input" name="note" placeholder="Không bắt buộc"/></div></div><div className="modal-actions"><button type="button" className="button secondary" onClick={()=>setRateCompany(undefined)}>Hủy</button><button className="button primary" disabled={saving}>{saving?"Đang lưu…":"Lưu mức lương"}</button></div></form></Modal>}
 <Toast message={msg} kind={kind} onClose={()=>setMsg("")}/></>
}
