"use client";
import { useCallback,useEffect,useState } from "react";
import Link from "next/link";
import { ArrowDownLeft,ArrowUpRight,BriefcaseBusiness,Building2,CalendarDays,ChartNoAxesCombined,Coins,Landmark,Plus,Wallet } from "lucide-react";
import { Area,AreaChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis,BarChart,Bar } from "recharts";
import { getDashboard,save } from "@/services/api";
import type { DashboardData } from "@/types";
import { currentMonth,todayISO,formatDate } from "@/lib/dates";
import { money,number } from "@/lib/format";
import { Modal } from "./Modal";
import { Toast } from "./Toast";
import { Loading } from "./Loading";
const initial:DashboardData={finance:{cash:0,accounts:0,investments:0,loans:0,assets:0,daily:[]},attendance:{days:0,hours:0,pay:0,companies:[],daily:[],monthly:[]}};
export function Dashboard(){
 const [month,setMonth]=useState(currentMonth()),[company,setCompany]=useState(""),[data,setData]=useState<DashboardData>(),[busy,setBusy]=useState(true),[error,setError]=useState(""),[quick,setQuick]=useState<"Thu"|"Chi"|null>(null),[msg,setMsg]=useState(""),[kind,setKind]=useState<"success"|"error">("success"),[saving,setSaving]=useState(false);
 const refresh=useCallback(async()=>{setBusy(true);setError("");try{setData(await getDashboard(month,company))}catch(e){setError((e as Error).message)}finally{setBusy(false)}},[month,company]);
 useEffect(()=>{refresh()},[refresh]);
 const d=data||initial, chartDays=d.finance.daily.map(x=>({day:x.date.slice(-2),income:x.income,expense:x.expense})),attDays=d.attendance.daily.map(x=>({day:x.date.slice(-2),hours:x.hours}));
 async function quickSave(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);const fd=new FormData(e.currentTarget);const method=String(fd.get("method"));const amount=Number(fd.get("amount"));try{await save(method,{date:String(fd.get("date")),amount:quick==="Chi"?-Math.abs(amount):Math.abs(amount),description:String(fd.get("description")||""),note:String(fd.get("description")||"")});setKind("success");setMsg(quick==="Chi"?"Đã thêm khoản chi.":"Đã thêm khoản thu.");setQuick(null);await refresh()}catch(err){setKind("error");setMsg((err as Error).message)}finally{setSaving(false)}}
 const Metric=({label,value,Icon,note,total=false}:{label:string;value:number;Icon:any;note?:string;total?:boolean})=><div className={"card metric "+(total?"total":"")}><div className="metric-head">{label}<span className="metric-icon"><Icon size={15}/></span></div><div className="metric-value">{money(value)}</div>{note&&<div className="metric-note">{note}</div>}</div>;
 return <><header className="page-top"><div><div className="eyebrow">Ngày {formatDate(todayISO())} · không gian của bạn</div><h1 className="page-title">Tổng quan</h1><p className="page-subtitle">Tình hình tài chính và công việc, gói gọn trong một nơi.</p></div><div className="top-actions"><input aria-label="Chọn tháng" className="input compact month-picker" type="month" value={month} onChange={e=>setMonth(e.target.value)}/></div></header>
 {busy&&!data?<Loading/>:error?<div className="error-box">{error}<br/><button className="button secondary small" style={{marginTop:12}} onClick={refresh}>Thử lại</button></div>:<><div className="section-head" style={{marginTop:0}}><div className="eyebrow">Tài chính cá nhân</div><Link href="/finance" className="button ghost small">Xem tài chính →</Link></div>
 <section className="metrics"><Metric label="Tiền mặt" value={d.finance.cash} Icon={Wallet} note="Số dư từ sổ giao dịch"/><Metric label="Tiền tài khoản" value={d.finance.accounts} Icon={Landmark} note="Số dư ngân hàng"/><Metric label="Giá trị đầu tư" value={d.finance.investments} Icon={ChartNoAxesCombined} note="Giá trị hiện tại"/><Metric label="Đang cho vay" value={d.finance.loans} Icon={ArrowUpRight} note="Còn phải thu"/><Metric label="Tổng tài sản" value={d.finance.assets} Icon={Coins} total note="Tài sản ròng hiện tại"/></section>
 <div className="overview-grid"><section className="card chart-card"><div className="card-head"><div><h2 className="card-title">Thu & chi trong tháng</h2><div className="card-caption">Theo ngày phát sinh từ sổ tiền mặt</div></div><span className="pill">Tiền mặt</span></div><div className="chart-wrap">{chartDays.length?<ResponsiveContainer width="100%" height="100%"><AreaChart data={chartDays}><defs><linearGradient id="inc" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#4e9b70" stopOpacity={.2}/><stop offset="1" stopColor="#4e9b70" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#edf1ed" vertical={false}/><XAxis dataKey="day" tickLine={false} axisLine={false} tick={{fontSize:9,fill:"#929b94"}}/><YAxis tickLine={false} axisLine={false} tick={{fontSize:9,fill:"#929b94"}} width={45}/><Tooltip formatter={(v:any)=>money(Number(v))}/><Area type="monotone" dataKey="income" name="Thu" stroke="#4e9b70" fill="url(#inc)" strokeWidth={2}/><Area type="monotone" dataKey="expense" name="Chi" stroke="#db8b6f" fill="transparent" strokeWidth={2}/></AreaChart></ResponsiveContainer>:<div className="empty">Chưa có giao dịch trong tháng này.</div>}</div></section>
 <section className="card chart-card"><div className="card-head"><div><h2 className="card-title">Giờ làm theo ngày</h2><div className="card-caption">Chọn công ty để lọc dữ liệu</div></div><select className="input compact" value={company} onChange={e=>setCompany(e.target.value)}><option value="">Tất cả công ty</option>{d.attendance.companies.map(c=><option key={c}>{c}</option>)}</select></div><div className="chart-wrap">{attDays.length?<ResponsiveContainer width="100%" height="100%"><BarChart data={attDays}><CartesianGrid stroke="#edf1ed" vertical={false}/><XAxis dataKey="day" tickLine={false} axisLine={false} tick={{fontSize:9,fill:"#929b94"}}/><YAxis tickLine={false} axisLine={false} tick={{fontSize:9,fill:"#929b94"}} width={35}/><Tooltip formatter={(v:any)=>number(Number(v))+" giờ"}/><Bar dataKey="hours" name="Số giờ" fill="#4c8e69" radius={[4,4,0,0]} maxBarSize={25}/></BarChart></ResponsiveContainer>:<div className="empty">Chưa có ngày công trong tháng này.</div>}</div></section></div>
 <div className="dashboard-bottom"><section className="card attendance-summary"><div className="summary-heading"><div><h2 className="card-title">Chấm công tháng này</h2><div className="card-caption">Tổng hợp cho tháng đang chọn</div></div><Link href="/attendance" className="button ghost small">Chi tiết →</Link></div><div className="summary-grid"><div className="summary-tile"><label>Ngày công</label><b>{d.attendance.days} ngày</b></div><div className="summary-tile"><label>Tổng giờ</label><b>{number(d.attendance.hours)} giờ</b></div><div className="summary-tile"><label>Tiền công</label><b>{money(d.attendance.pay)}</b></div></div></section><section className="card quick-actions"><div><h2 className="card-title">Thao tác nhanh</h2><div className="card-caption">Ghi nhận ngay khi phát sinh</div></div><div className="button-row"><button className="button secondary" onClick={()=>setQuick("Chi")}><ArrowDownLeft size={15}/> Chi tiền</button><button className="button secondary" onClick={()=>setQuick("Thu")}><ArrowUpRight size={15}/> Thu tiền</button><Link className="button primary" href="/attendance"><Plus size={15}/> Chấm công</Link></div></section></div>
 <section className="card chart-card" style={{marginTop:15,minHeight:245}}><div className="card-head"><div><h2 className="card-title">Tiền công theo tháng</h2><div className="card-caption">12 tháng gần nhất · từ dữ liệu chấm công</div></div></div><div className="chart-wrap">{d.attendance.monthly.length?<ResponsiveContainer width="100%" height="100%"><BarChart data={d.attendance.monthly}><CartesianGrid stroke="#edf1ed" vertical={false}/><XAxis dataKey="month" tickLine={false} axisLine={false} tick={{fontSize:9,fill:"#929b94"}}/><YAxis tickLine={false} axisLine={false} tick={{fontSize:9,fill:"#929b94"}} width={50}/><Tooltip formatter={(v:any)=>money(Number(v))}/><Bar dataKey="pay" name="Tiền công" fill="#719e7a" radius={[4,4,0,0]} maxBarSize={38}/></BarChart></ResponsiveContainer>:<div className="empty">Chưa có lịch sử chấm công.</div>}</div></section></>}
 {quick&&<Modal title={quick==="Chi"?"Ghi nhận khoản chi":"Ghi nhận khoản thu"} onClose={()=>setQuick(null)}><form onSubmit={quickSave}><div className="form-grid"><div className="field"><label>Ngày</label><input className="input" type="date" name="date" defaultValue={todayISO()} required/></div><div className="field"><label>Lưu vào</label><select className="input" name="method"><option value="cash">Tiền mặt</option><option value="accounts">Tài khoản</option></select></div><div className="field wide"><label>Số tiền</label><input className="input" type="number" min="1" step="any" name="amount" required placeholder="0"/></div><div className="field wide"><label>Mô tả / ghi chú</label><input className="input" name="description" required placeholder="Ví dụ: ăn trưa"/></div></div><div className="modal-actions"><button type="button" className="button secondary" onClick={()=>setQuick(null)}>Hủy</button><button className="button primary" disabled={saving}>{saving?<><span className="spinner"/> Đang lưu</>:<><Plus size={15}/> Lưu giao dịch</>}</button></div></form></Modal>}
 <Toast message={msg} kind={kind} onClose={()=>setMsg("")}/></>
}
