"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import { ArrowDownLeft,ArrowUpRight,Check,Edit2,Plus,Trash2,Wallet,Landmark,ChartNoAxesCombined,HandCoins } from "lucide-react";
import { getData,save,remove } from "@/services/api";
import type { AppData,AccountTransaction,CashTransaction,Investment,Loan } from "@/types";
import { todayISO,formatDate,dateRange } from "@/lib/dates";
import { money } from "@/lib/format";
import { Modal } from "./Modal";
import { Toast } from "./Toast";
import { Loading } from "./Loading";
type Tab="cash"|"accounts"|"investments"|"loans";
const financeTabs:{key:Tab;label:string;Icon:typeof Wallet}[]=[
 {key:"cash",label:"Tiền mặt",Icon:Wallet},{key:"accounts",label:"Tài khoản",Icon:Landmark},
 {key:"investments",label:"Đầu tư",Icon:ChartNoAxesCombined},{key:"loans",label:"Cho vay",Icon:HandCoins},
];
const zero:AppData={cash:[],accounts:[],investments:[],loans:[],companies:[],rates:[],attendance:[]};
export function Finance(){
 const [tab,setTab]=useState<Tab>("cash"),[data,setData]=useState<AppData>(),[busy,setBusy]=useState(true),[loadError,setLoadError]=useState(""),[modal,setModal]=useState(false),[editing,setEditing]=useState<any>(),[msg,setMsg]=useState(""),[kind,setKind]=useState<"success"|"error">("success"),[saving,setSaving]=useState(false),[from,setFrom]=useState(""),[to,setTo]=useState(""),[direction,setDirection]=useState(""),[preset,setPreset]=useState("");
 const refresh=useCallback(async()=>{setBusy(true);setLoadError("");try{const partial=await getData([tab]);setData(previous=>({...zero,...previous,...partial}))}catch(e){const message=(e as Error).message;setLoadError(message);setKind("error");setMsg(message)}finally{setBusy(false)}},[tab]);
 useEffect(()=>{refresh()},[refresh]);const d=data||zero;
 const rows=useMemo(()=>{let list:any[]=[...d[tab]];if(["cash","accounts"].includes(tab)){if(from)list=list.filter(x=>x.date>=from);if(to)list=list.filter(x=>x.date<=to);if(direction==="income")list=list.filter(x=>x.amount>0);if(direction==="expense")list=list.filter(x=>x.amount<0)}return list.reverse()},[d,tab,from,to,direction]);
 const invested=d.investments.reduce((s,x)=>s+x.principal,0),market=d.investments.reduce((s,x)=>s+x.currentValue,0),loanOutstanding=d.loans.reduce((s,x)=>s+x.remaining,0),recovered=d.loans.filter(x=>x.status==="Đã trả").reduce((s,x)=>s+x.amount,0);
 function formSubmit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget),v:any={};fd.forEach((x,k)=>v[k]=x);if(tab==="cash"||tab==="accounts"){v.amount=Math.abs(Number(v.amount))*(v.type==="Chi"?-1:1);delete v.type}for(const k of ["principal","currentValue","amount","interestRate"])if(v[k]!==undefined)v[k]=Number(v[k]);if(tab==="loans")v.remaining=v.status==="Đã trả"?0:v.amount;setSaving(true);save(tab,v,editing?.id).then(async()=>{setKind("success");setMsg(editing?"Đã cập nhật dữ liệu.":"Đã thêm dữ liệu.");setModal(false);setEditing(undefined);await refresh()}).catch(e=>{setKind("error");setMsg(e.message)}).finally(()=>setSaving(false))}
 async function del(id:string){if(!window.confirm("Bạn có chắc muốn xóa dữ liệu này? Thao tác sẽ xóa dòng khỏi Google Sheets."))return;try{await remove(tab,id);setKind("success");setMsg(tab==="loans"?"Đã xóa khoản cho vay.":"Đã xóa dữ liệu.");await refresh()}catch(e){setKind("error");setMsg((e as Error).message)}}
 async function repaid(x:Loan){try{await save("loans",{...x,status:"Đã trả",remaining:0},x.id);setKind("success");setMsg("Đã đánh dấu khoản vay đã trả.");await refresh()}catch(e){setKind("error");setMsg((e as Error).message)}}
 const config={cash:{title:"Tiền mặt",desc:"Ghi lại tiền vào và các khoản chi tiêu tiền mặt.",Icon:Wallet},accounts:{title:"Tài khoản",desc:"Theo dõi giao dịch và số dư trong tài khoản.",Icon:Landmark},investments:{title:"Đầu tư",desc:"Theo dõi vốn, giá trị hiện tại và hiệu quả đầu tư.",Icon:ChartNoAxesCombined},loans:{title:"Cho vay",desc:"Quản lý các khoản cho vay và tiền còn phải thu.",Icon:HandCoins}}[tab];
 return <><header className="page-top"><div><div className="eyebrow">Sổ sách cá nhân</div><h1 className="page-title">Tài chính</h1><p className="page-subtitle">Mỗi giao dịch là một dòng dữ liệu, không cần tạo sổ theo tháng.</p></div><button className="button primary" onClick={()=>{setEditing(undefined);setModal(true)}}><Plus size={16}/> Thêm {tab==="cash"?"giao dịch":tab==="accounts"?"giao dịch":tab==="investments"?"khoản đầu tư":"khoản cho vay"}</button></header>
  <div className="tabs">{financeTabs.map(({key,label,Icon})=><button key={key} className={"tab "+(tab===key?"active":"")} onClick={()=>{setTab(key);setFrom("");setTo("");setDirection("");setPreset("")}}><Icon size={14}/>  {label}</button>)}</div>
 <div className="section-head" style={{marginTop:5}}><div><h2 className="card-title">{config.title}</h2><div className="card-caption">{config.desc}</div></div></div>
 {tab==="investments"&&<div className="metrics" style={{gridTemplateColumns:"repeat(3,1fr)",marginTop:12}}><div className="card metric"><div className="metric-head">Tổng vốn <span className="metric-icon"><Wallet size={15}/></span></div><div className="metric-value">{money(invested)}</div></div><div className="card metric"><div className="metric-head">Giá trị hiện tại <span className="metric-icon"><ChartNoAxesCombined size={15}/></span></div><div className="metric-value">{money(market)}</div></div><div className="card metric"><div className="metric-head">Lãi / lỗ <span className="metric-icon"><ArrowUpRight size={15}/></span></div><div className={"metric-value "+(market-invested<0?"amount-negative":"amount-positive")}>{money(market-invested)}</div></div></div>}
 {tab==="loans"&&<div className="metrics" style={{gridTemplateColumns:"repeat(3,1fr)",marginTop:12}}><div className="card metric"><div className="metric-head">Đang cho vay</div><div className="metric-value">{money(d.loans.reduce((s,x)=>s+x.amount,0))}</div></div><div className="card metric"><div className="metric-head">Đã thu hồi</div><div className="metric-value">{money(recovered)}</div></div><div className="card metric total"><div className="metric-head">Còn phải thu</div><div className="metric-value">{money(loanOutstanding)}</div></div></div>}
 {["cash","accounts"].includes(tab)&&<div className="filter-bar"><div className="filters"><div className="field"><label>Khoảng thời gian</label><select className="input compact" value={preset} onChange={e=>{setPreset(e.target.value);if(e.target.value){const r=dateRange(e.target.value);setFrom(r.from);setTo(r.to)}}}><option value="">Tùy chọn</option><option value="today">Hôm nay</option><option value="week">Tuần này</option><option value="month">Tháng này</option><option value="previous">Tháng trước</option></select></div><div className="field"><label>Từ ngày</label><input className="input compact" type="date" value={from} onChange={e=>{setPreset("");setFrom(e.target.value)}}/></div><div className="field"><label>Đến ngày</label><input className="input compact" type="date" value={to} onChange={e=>{setPreset("");setTo(e.target.value)}}/></div><div className="field"><label>Loại</label><select className="input compact" value={direction} onChange={e=>setDirection(e.target.value)}><option value="">Tất cả</option><option value="income">Thu</option><option value="expense">Chi</option></select></div></div><div className="muted" style={{fontSize:11}}>{rows.length} giao dịch</div></div>}
 {busy&&!data?<Loading/>:loadError&&!data?<div className="error-box">{loadError}<br/><button className="button secondary small" style={{marginTop:12}} onClick={refresh}>Thử lại</button></div>: <div className="card table-card"><div className="table-scroll"><table className="data-table"><thead>{tab==="cash"?<tr><th>Ngày</th><th>Mô tả</th><th className="right">Số tiền</th><th className="right">Số dư</th><th/> </tr>:tab==="accounts"?<tr><th>Ngày</th><th>Ghi chú</th><th className="right">Số tiền</th><th className="right">Số dư</th><th/></tr>:tab==="investments"?<tr><th>Loại đầu tư</th><th>Tên</th><th className="right">Số vốn</th><th className="right">Giá trị hiện tại</th><th className="right">Lãi / lỗ</th><th/></tr>:<tr><th>Người vay</th><th>Ngày cho vay</th><th className="right">Số tiền</th><th>Lãi suất</th><th>Ngày trả</th><th>Trạng thái</th><th className="right">Còn lại</th><th/></tr>}</thead><tbody>{rows.map((x:any)=><tr key={x.id}>{tab==="cash"?<><td>{formatDate(x.date)}</td><td>{x.description||<span className="muted">Chưa có mô tả</span>}</td><td className={"right "+(x.amount>=0?"amount-positive":"amount-negative")}>{money(x.amount)}</td><td className="right">{money(x.balance)}</td></>:tab==="accounts"?<><td>{formatDate(x.date)}</td><td>{x.note||"—"}</td><td className={"right "+(x.amount>=0?"amount-positive":"amount-negative")}>{money(x.amount)}</td><td className="right">{money(x.balance)}</td></>:tab==="investments"?<><td>{x.type||"—"}</td><td>{x.name}</td><td className="right">{money(x.principal)}</td><td className="right">{money(x.currentValue)}</td><td className={"right "+(x.profitLoss>=0?"amount-positive":"amount-negative")}>{money(x.profitLoss)}</td></>:<><td>{x.borrower}</td><td>{formatDate(x.loanDate)}</td><td className="right">{money(x.amount)}</td><td>{x.interestRate?x.interestRate+"%":"—"}</td><td>{formatDate(x.dueDate)}</td><td><span className={"pill "+(x.status==="Đã trả"?"gray":"")}>{x.status}</span></td><td className="right">{money(x.remaining)}</td></>}<td><div className="row-actions">{tab==="loans"&&x.status!=="Đã trả"&&<button className="icon-button" title="Đánh dấu đã trả" onClick={()=>repaid(x)}><Check size={15}/></button>}<button className="icon-button" title="Sửa" onClick={()=>{setEditing(x);setModal(true)}}><Edit2 size={14}/></button><button className="icon-button" title="Xóa" onClick={()=>del(x.id)}><Trash2 size={14}/></button></div></td></tr>)}</tbody></table></div>{!rows.length&&<div className="empty">Chưa có dữ liệu. Bấm “Thêm” để ghi nhận dòng đầu tiên.</div>}</div>}
 {modal&&<Modal title={(editing?"Cập nhật ":"Thêm ")+({cash:"giao dịch tiền mặt",accounts:"giao dịch tài khoản",investments:"khoản đầu tư",loans:"khoản cho vay"}[tab])} onClose={()=>{setModal(false);setEditing(undefined)}}><form onSubmit={formSubmit}><div className="form-grid">
 {["cash","accounts"].includes(tab)&&<><div className="field"><label>Ngày</label><input className="input" type="date" name="date" defaultValue={editing?.date||todayISO()} required/></div><div className="field"><label>Loại giao dịch</label><select className="input" name="type" defaultValue={editing?(editing.amount<0?"Chi":"Thu"):"Chi"}><option>Thu</option><option>Chi</option></select></div><div className="field wide"><label>Số tiền</label><input className="input" name="amount" type="number" min="0.01" step="any" defaultValue={editing?Math.abs(editing.amount):""} required/></div><div className="field wide"><label>{tab==="cash"?"Mô tả":"Ghi chú"}</label><input className="input" name={tab==="cash"?"description":"note"} defaultValue={editing?.description||editing?.note||""} required={tab==="cash"}/></div></>}
 {tab==="investments"&&<><div className="field"><label>Loại đầu tư</label><input className="input" name="type" defaultValue={editing?.type||""} placeholder="Ví dụ: Tiết kiệm"/></div><div className="field"><label>Tên khoản</label><input className="input" name="name" defaultValue={editing?.name||""} required/></div><div className="field"><label>Số vốn</label><input className="input" name="principal" type="number" min="0" step="any" defaultValue={editing?.principal??""} required/></div><div className="field"><label>Giá trị hiện tại</label><input className="input" name="currentValue" type="number" min="0" step="any" defaultValue={editing?.currentValue??""} required/></div></>}
 {tab==="loans"&&<><div className="field"><label>Người vay</label><input className="input" name="borrower" defaultValue={editing?.borrower||""} required/></div><div className="field"><label>Ngày cho vay</label><input className="input" name="loanDate" type="date" defaultValue={editing?.loanDate||todayISO()}/></div><div className="field"><label>Số tiền</label><input className="input" name="amount" type="number" min="0.01" step="any" defaultValue={editing?.amount??""} required/></div><div className="field"><label>Lãi suất (%)</label><input className="input" name="interestRate" type="number" min="0" step="any" defaultValue={editing?.interestRate||""}/></div><div className="field"><label>Ngày trả dự kiến</label><input className="input" name="dueDate" type="date" defaultValue={editing?.dueDate||""}/></div><div className="field"><label>Trạng thái</label><select className="input" name="status" defaultValue={editing?.status||"Chưa trả"}><option>Chưa trả</option><option>Đã trả</option></select></div><div className="field wide"><label>Ghi chú</label><input className="input" name="note" defaultValue={editing?.note||""}/></div></>}
 </div><div className="modal-actions"><button type="button" className="button secondary" onClick={()=>setModal(false)}>Hủy</button><button className="button primary" disabled={saving}>{saving?<><span className="spinner"/> Đang lưu</>:"Lưu thay đổi"}</button></div></form></Modal>}
 <Toast message={msg} kind={kind} onClose={()=>setMsg("")}/></>
}
